# Задание 1.

Проанализируйте текст ниже с помощью майстема. Уберите из получившегося списка элементы, у которых нет грамматического разбора.
Далее создайте отдельный список только с частями речи для каждого слова.
Превратите этот список отдельных частеречных тэгов в список частеречных триграммов (с пересечением).
`['N', "ADJ", "V", "J"] -> [("N", "ADJ", "V"), ("ADJ", "V", ""J")]` (тэги не настоящие для примера)

Найдите самый частотный частеречный триграмм. Вставьте триграмм и количество вхождений в форму в таком формате:

`N ADJ V;3` (три тэга через пробел и количество вхождение через точку с запятой)


In [35]:
text = """
Античит-движки для игр — это ещё одна крупная область Windows, которая использует драйверы на уровне ядра. Microsoft ведёт переговоры с разработчиками игр о том, как сократить объём использования ядра. Riot Games сообщила Microsoft о готовности следовать потенциальным изменениям безопасности Windows и сократить влияние на ядро ОС.

Летом этого года Microsoft готовится к выпуску обновления Windows, которое будет включать новую функцию Quick Machine Recovery. Функция предназначена для быстрого восстановления системы после сбоя. Ранее Microsoft сообщила о планах сменить синий экран смерти на чёрный.
"""

In [36]:
from pymystem3 import Mystem
from collections import Counter
import re

m = Mystem()
parsed = m.analyze(text)

tags = [item['analysis'][0]['gr'] for item in parsed if 'analysis' in item and item['analysis']]
pos_tags = [re.split('[,=]', tag)[0] for tag in tags]
trigrams = [(pos_tags[i], pos_tags[i+1], pos_tags[i+2]) for i in range(len(pos_tags)-2)]
trigram_counts = Counter(trigrams)
most_common_trigram, freq = trigram_counts.most_common(1)[0]


print(f"{most_common_trigram[0]} {most_common_trigram[1]} {most_common_trigram[2]};{freq}")

S PR S;5


## Задание 2.

Вам дана последовательность с правильными ответами для задачи многоклассовой классификации. А также массив с предсказаниями такой же длины, но в виде вероятностей для каждого класса. Для каждой строчки выберете самый вероятный класс.

Рассчитайте TP,FP,TN,FN для каждого класса. Рассчитайте точность для каждого класса по отдельности. Найдите класс с самой высокой точностью и вставьте значение точности для этого класса в форму как ответ. Округлите ответ до 2 знака после запятой (например, `0.12`)

*Для этого задания не используйте готовые решения (можно использовать только numpy для работы с массивом вероятностей и встроенные библиотеки вроде collections.Counter для удобства)

In [37]:
import numpy as np
from collections import Counter

In [38]:
multiclass_true = [0,3,0,0,3,0,0,1,2,4,1,2,4,0,2,0,4,1,2,4,1,1,4,1,2,0]


In [39]:
probas = np.array([[0.14283307, 0.69125398, 0.08801677, 0.05890497, 0.01899121],
       [0.05017326, 0.16837714, 0.09787715, 0.37586925, 0.3077032 ],
       [0.07349622, 0.20737874, 0.06666821, 0.0582571 , 0.59419973],
       [0.08704361, 0.18970222, 0.16262277, 0.08630088, 0.47433053],
       [0.16137361, 0.21450292, 0.22870402, 0.24422044, 0.151199  ],
       [0.268094  , 0.43761478, 0.12385365, 0.04917541, 0.12126215],
       [0.27161954, 0.01412896, 0.11056462, 0.09468905, 0.50899783],
       [0.09363269, 0.02693918, 0.33977914, 0.39909705, 0.14055195],
       [0.29520778, 0.05132426, 0.06673668, 0.45254433, 0.13418695],
       [0.15421375, 0.22964685, 0.16662999, 0.21004033, 0.23946907],
       [0.24755032, 0.24628846, 0.12956078, 0.24832473, 0.12827571],
       [0.11797719, 0.03232272, 0.07293219, 0.52455883, 0.25220907],
       [0.75835945, 0.07189134, 0.06032446, 0.04986686, 0.05955789],
       [0.02601848, 0.26673495, 0.03124844, 0.21992134, 0.4560768 ],
       [0.58059452, 0.03148405, 0.11400383, 0.14452069, 0.12939691],
       [0.08215579, 0.32887402, 0.10776154, 0.30880314, 0.17240552],
       [0.11467395, 0.07250172, 0.03868279, 0.04358503, 0.73055651],
       [0.09546111, 0.22318028, 0.04797582, 0.42230537, 0.21107742],
       [0.17088269, 0.31617363, 0.02329777, 0.26480448, 0.22484143],
       [0.1573525 , 0.04416687, 0.59056588, 0.0854817 , 0.12243306],
       [0.16300152, 0.224168  , 0.11143585, 0.09995103, 0.4014436 ],
       [0.17649215, 0.32146966, 0.21575183, 0.0238604 , 0.26242596],
       [0.00860468, 0.01201256, 0.96059244, 0.00327634, 0.01551398],
       [0.06455855, 0.11772163, 0.25971348, 0.32510222, 0.23290411],
       [0.04150647, 0.1329052 , 0.22146507, 0.03930956, 0.5648137 ],
       [0.12671909, 0.01486602, 0.77637796, 0.06239952, 0.01963741]])

In [40]:
import numpy as np

predicted = np.argmax(probas, axis=1)
num_classes = probas.shape[1]

TP = np.zeros(num_classes, dtype=int)
FP = np.zeros(num_classes, dtype=int)
FN = np.zeros(num_classes, dtype=int)
TN = np.zeros(num_classes, dtype=int)

for true, pred in zip(multiclass_true, predicted):
    for cls in range(num_classes):
        if true == cls and pred == cls:
            TP[cls] += 1
        elif pred == cls and true != cls:
            FP[cls] += 1
        elif true == cls and pred != cls:
            FN[cls] += 1
        else:
            TN[cls] += 1

precisions = np.divide(TP, TP + FP, out=np.zeros_like(TP, dtype=float), where=(TP + FP) != 0)
max_precision = round(np.max(precisions), 2)
print(max_precision)

0.25


In [41]:
TP, FP, FN, TN

(array([0, 1, 0, 2, 2]),
 array([2, 4, 3, 6, 6]),
 array([8, 5, 5, 0, 3]),
 array([16, 16, 18, 18, 15]))

## Задание 3

Загрузите токенизатор и модель `sentence-transformers/all-MiniLM-L6-v2`. Токенизируйте и рассчитайте векторные представления для двух приведенных ниже текстов. Усредните векторные представления токенов каждого из текстов так, чтобы для каждого из текстов получился вектор размером 384.
Рассчитайте косинусную близость между двумя этим векторами, округлите его до 2 знака после запятой и вставьте число в форму.


In [42]:
text1 = "Hounds display remarkable fidelity towards their owners, often brightening days through affectionate gestures."
text2 = "Domestic pups exhibit steadfast allegiance to caregivers, frequently lifting spirits via tender behaviors."

In [43]:
from transformers import AutoTokenizer, AutoModel
import torch
import torch.nn.functional as F

model_name = "sentence-transformers/all-MiniLM-L6-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
model.eval()

def mean_token_embedding(text: str) -> torch.Tensor:
    encoded = tokenizer(text, return_tensors="pt")
    attention_mask = encoded["attention_mask"]

    with torch.no_grad():
        outputs = model(**encoded)

    last_hidden = outputs.last_hidden_state.squeeze(0)
    mask = attention_mask.squeeze(0).bool()
    token_vecs = last_hidden[mask]
    return token_vecs.mean(dim=0)

vec1 = mean_token_embedding(text1)
vec2 = mean_token_embedding(text2)

cos_sim = F.cosine_similarity(vec1.unsqueeze(0), vec2.unsqueeze(0)).item()

print(f"{cos_sim:.2f}")

0.64


# Задание 4

Используя модель "HuggingFaceTB/SmolLM2-135M" (huggingface), сгенерируйте продолжение следующего промпта:
"I woke up and saw ".

Используйте следующее параметры при генерации: максимальная длина продолжения - 40 токенов, отсутствие повторов длиной 2 токена, отсутствие семплирования (выбирается только самый вероятный токен).

Модель должна быть загружена в 4bit формате.

Вставьте сгенерированный текст в форму целиком (кавычки лучше не включать, но сработает и с ними)



In [44]:
!pip install bitsandbytes

In [45]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16
)

model_name = "HuggingFaceTB/SmolLM2-135M"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=quantization_config,
    device_map="auto"
)

prompt = "I woke up and saw "
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.to(model.device)

output = model.generate(
    input_ids,
    max_new_tokens=40,
    no_repeat_ngram_size=2,
    do_sample=False,
    num_beams=1,
    pad_token_id=tokenizer.eos_token_id
)

continuation = tokenizer.decode(
    output[0][len(input_ids[0]):],
    skip_special_tokens=True
)
print(continuation)

12, 23, and 33.  I had to go to the hospital to get the 43 and the other 53 were all in the same hospital.
